# Generated by Django 5.2.5 on 2025-09-23 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('compliance_monitoring', '0006_remove_project_auditors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditors', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_auditors', to='compliance_monitoring.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
