# Generated by Django 5.2.5 on 2025-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditors',
            options={'verbose_name': 'Auditor Assignment', 'verbose_name_plural': 'Auditor Assignments'},
        ),
    ]
