# Generated by Django 5.2.5 on 2025-09-03 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the compliance framework (e.g., 'ISO 27001:2022').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the framework.')),
            ],
            options={
                'verbose_name': 'Framework',
                'verbose_name_plural': 'Frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(help_text="The identifier for the clause (e.g., 'A.5.1').", max_length=50)),
                ('title', models.CharField(help_text='The title of the clause.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The detailed description or requirements of the clause.')),
                ('framework', models.ForeignKey(help_text='The framework this clause belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='compliance_monitoring.framework')),
            ],
            options={
                'verbose_name': 'Clause',
                'verbose_name_plural': 'Clauses',
                'ordering': ['framework', 'clause_number'],
                'unique_together': {('framework', 'clause_number')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the project.')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('At Risk', 'At Risk')], default='Not Started', help_text='The current status of the project.', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0, help_text='The completion percentage of the project (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(help_text='The compliance framework this project is based on.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='compliance_monitoring.framework')),
                ('organization', models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who owns this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_clause_number', models.CharField(help_text="The identifier for the sub-clause (e.g., 'a', '1', 'i').", max_length=50)),
                ('title', models.CharField(help_text='The title of the sub-clause.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The detailed description or requirements of the sub-clause.')),
                ('clause', models.ForeignKey(help_text='The parent clause this sub-clause belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_clauses', to='compliance_monitoring.clause')),
            ],
            options={
                'verbose_name': 'Sub-Clause',
                'verbose_name_plural': 'Sub-Clauses',
                'ordering': ['clause', 'sub_clause_number'],
                'unique_together': {('clause', 'sub_clause_number')},
            },
        ),
    ]
