# Generated by Django 5.2.5 on 2025-09-11 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auditor',
            field=models.ManyToManyField(blank=True, help_text='Users assigned as auditors for this project.', related_name='audited_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='auditor_enabled',
            field=models.BooleanField(default=False, help_text='Indicates if auditors are enabled for this project.'),
        ),
    ]
