# Generated by Django 5.2.5 on 2025-09-11 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0002_project_auditor_project_auditor_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='auditor',
            field=models.ManyToManyField(blank=True, help_text='Users assigned as auditors for this project.', null=True, related_name='audited_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
