# Generated by Django 5.2.5 on 2025-09-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0003_alter_project_auditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auditor',
        ),
    ]
