# Generated by Django 5.2.5 on 2025-09-23 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0004_remove_project_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auditors',
            field=models.ManyToManyField(blank=True, help_text='Users assigned as auditors for this project.', related_name='audited_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
