# Generated by Django 5.2.5 on 2025-09-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0005_project_auditors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auditors',
        ),
    ]
