# Generated by Django 5.2.5 on 2025-09-25 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_monitoring', '0006_remove_project_auditors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who owns this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', help_text='The permission level for this user on this project.', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='The user who added this member to the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='compliance_monitoring.project')),
                ('user', models.ForeignKey(help_text='The user who is a member of this project.', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
