# Generated by Django 5.1.3 on 2025-10-09 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('project_url', models.CharField(blank=True, max_length=500)),
                ('overall_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('critical_risks', models.IntegerField(default=0)),
                ('high_risks', models.IntegerField(default=0)),
                ('medium_risks', models.IntegerField(default=0)),
                ('low_risks', models.IntegerField(default=0)),
                ('total_risks', models.IntegerField(default=0)),
                ('total_data_points', models.IntegerField(default=0)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('full_report', models.JSONField(default=dict)),
                ('used_git_scan', models.BooleanField(default=False)),
                ('used_sast_scan', models.BooleanField(default=False)),
                ('used_mobile_scan', models.BooleanField(default=False)),
                ('used_security_headers', models.BooleanField(default=False)),
                ('used_cookie_analysis', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pia_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIA Result',
                'verbose_name_plural': 'PIA Results',
                'ordering': ['-generated_at'],
            },
        ),
    ]
