# Generated by Django 5.2.5 on 2025-10-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_detection', '0004_roparesult'),
    ]

    operations = [
        migrations.AddField(
            model_name='roparesult',
            name='privacy_project',
            field=models.ForeignKey(blank=True, help_text='Related privacy detection project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ropa_results', to='privacy_detection.privacydetectionproject'),
        ),
        migrations.AlterField(
            model_name='dpiaresult',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project being assessed', max_length=255),
        ),
        migrations.AlterField(
            model_name='piaresult',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project being assessed', max_length=255),
        ),
        migrations.AlterField(
            model_name='roparesult',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project being assessed', max_length=255),
        ),
    ]
