# Generated by Django 5.1.3 on 2025-10-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_detection', '0005_add_privacy_project_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpiaresult',
            name='privacy_project',
            field=models.ForeignKey(blank=True, help_text='Related privacy detection project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpia_results', to='privacy_detection.privacydetectionproject'),
        ),
        migrations.AddField(
            model_name='piaresult',
            name='privacy_project',
            field=models.ForeignKey(blank=True, help_text='Related privacy detection project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pia_results', to='privacy_detection.privacydetectionproject'),
        ),
    ]
