# Generated by Django 5.2.5 on 2025-10-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Overall percentage score')),
                ('total_questions', models.IntegerField(help_text='Total number of questions')),
                ('met_count', models.IntegerField(help_text="Number of 'Met' responses")),
                ('not_met_count', models.IntegerField(help_text="Number of 'Not Met' responses")),
                ('not_applicable_count', models.IntegerField(help_text="Number of 'Not Applicable' responses")),
                ('applicable_questions', models.IntegerField(help_text='Total applicable questions (Met + Not Met)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_responses', models.JSONField(blank=True, default=dict, help_text='Raw question responses stored as JSON')),
                ('calculated_scores', models.JSONField(blank=True, default=dict, help_text='All calculated scores stored as JSON')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionnaire Result',
                'verbose_name_plural': 'Questionnaire Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of the category', max_length=200)),
                ('category_number', models.IntegerField(help_text='Category number/order')),
                ('category_score', models.IntegerField(help_text='Category percentage score')),
                ('total_questions', models.IntegerField(help_text='Total questions in this category')),
                ('met_count', models.IntegerField(help_text="Number of 'Met' responses in this category")),
                ('not_met_count', models.IntegerField(help_text="Number of 'Not Met' responses in this category")),
                ('not_applicable_count', models.IntegerField(help_text="Number of 'Not Applicable' responses in this category")),
                ('applicable_questions', models.IntegerField(help_text='Applicable questions in this category')),
                ('questionnaire_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='questionnaire.questionnaireresult')),
            ],
            options={
                'verbose_name': 'Category Score',
                'verbose_name_plural': 'Category Scores',
                'ordering': ['category_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField(help_text='Category number this question belongs to')),
                ('question_number', models.IntegerField(help_text='Question number within the category')),
                ('question_text', models.TextField(help_text='Full text of the question')),
                ('response', models.CharField(choices=[('Met', 'Met'), ('Not Met', 'Not Met'), ('Not Applicable', 'Not Applicable')], help_text="User's response to the question", max_length=20)),
                ('questionnaire_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='questionnaire.questionnaireresult')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
                'ordering': ['category_number', 'question_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoryscore',
            constraint=models.UniqueConstraint(fields=('questionnaire_result', 'category_number'), name='questionnaire_categoryscore_unique_result_category'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('questionnaire_result', 'category_number', 'question_number'), name='questionnaire_questionresponse_unique_result_category_question'),
        ),
    ]
