# Generated by Django 5.2.5 on 2025-09-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('action', models.CharField(help_text="A short description of the action, e.g., 'User logged in'.", max_length=255)),
                ('module', models.CharField(help_text="The application module where the action occurred, e.g., 'Authentication'.", max_length=100)),
                ('details', models.TextField(blank=True, help_text='Detailed information about the event, e.g., IP address, object ID.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action. Can be null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
