# Generated by Django 5.2.5 on 2025-09-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0001_initial'),
        ('compliance_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_name', models.CharField(help_text='A descriptive name for the evidence file.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the evidence.')),
                ('evidence_content', models.TextField(blank=True, help_text='The content of the evidence file.')),
                ('file', models.FileField(upload_to='evidence_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(help_text='The clause this evidence is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance_monitoring.clause')),
                ('project', models.ForeignKey(help_text='The project this evidence is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance_monitoring.project')),
                ('sub_clause', models.ForeignKey(help_text='The sub-clause this evidence is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance_monitoring.subclause')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
