# Generated by Django 5.2.5 on 2025-09-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_evidence'),
        ('compliance_monitoring', '0004_remove_project_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='clause',
            field=models.ForeignKey(blank=True, help_text='The clause this evidence is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='compliance_monitoring.clause'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='sub_clause',
            field=models.ForeignKey(blank=True, help_text='The sub-clause this evidence is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='compliance_monitoring.subclause'),
        ),
    ]
