# Generated by Django 5.2.5 on 2025-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0003_alter_evidence_clause_alter_evidence_sub_clause'),
        ('compliance_monitoring', '0004_remove_project_auditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='clause',
        ),
        migrations.AddField(
            model_name='evidence',
            name='clauses',
            field=models.ManyToManyField(blank=True, help_text='The clauses this evidence is associated with.', related_name='evidences', to='compliance_monitoring.clause'),
        ),
    ]
