# Generated by Django 5.2.5 on 2025-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0004_remove_evidence_clause_evidence_clauses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence_files/'),
        ),
    ]
