# Generated by Django 5.2.5 on 2025-09-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0005_alter_evidence_file'),
        ('compliance_monitoring', '0004_remove_project_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short title for the risk.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the risk.')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe')], default='low', help_text='The severity level of the risk.', max_length=10)),
                ('likelihood', models.CharField(choices=[('1', '1 - Very Unlikely'), ('2', '2 - Unlikely'), ('3', '3 - Possible'), ('4', '4 - Likely'), ('5', '5 - Very Likely')], default='3', help_text='The likelihood of the risk occurring, on a scale from 1 (low) to 5 (high).', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', help_text='The current status of the risk.', max_length=20)),
                ('risk_rating', models.CharField(help_text='The calculated risk rating based on likelihood and impact.', max_length=10)),
                ('target_mitigation_date', models.DateField(blank=True, help_text='The target date for mitigating the risk.', null=True)),
                ('mitigation_strategy', models.TextField(blank=True, help_text='The plan for mitigating the risk.')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The user responsible for managing this risk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this risk is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='compliance_monitoring.project')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
    ]
