# Generated by Django 5.2.5 on 2025-09-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0006_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='risk_level',
            new_name='impact',
        ),
    ]
