# Generated by Django 5.2.5 on 2025-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0007_rename_risk_level_risk_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='risk_category',
            field=models.CharField(choices=[('Compliance', 'Compliance'), ('Security', 'Security'), ('Financial', 'Financial'), ('Operational', 'Operational'), ('Technical', 'Technical')], default='Operational', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Severe', 'Severe')], default='Low', max_length=10),
        ),
    ]
