# Generated by Django 5.2.5 on 2025-09-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0008_risk_risk_category_alter_risk_impact'),
        ('compliance_monitoring', '0004_remove_project_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(help_text="Corresponds to the smaller text line, e.g., 'User Management'", max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Required', 'Action Required'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('category', models.CharField(choices=[('user_approval', 'User Approval'), ('risk_approval', 'Risk Approval'), ('auditor_assignment', 'Auditor Assignment'), ('evidence_approval', 'Evidence Approval'), ('policy_approval', 'Policy Approval'), ('Other', 'Other')], max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details in JSON format.')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='compliance_monitoring.project')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending Updates', 'Pending Updates')], max_length=20)),
                ('evidence_notes', models.TextField(blank=True, help_text='Notes on the evidence provided.')),
                ('conclusion', models.TextField(blank=True, help_text='Final conclusion of the review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='compliance_monitoring.clause')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance_monitoring.clause')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
