# Generated by Django 5.2.5 on 2025-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0009_actionitem_auditorreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorreview',
            name='evidence',
            field=models.TextField(blank=True, help_text='Evidence details for the review.'),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='has_upload_option',
            field=models.BooleanField(default=True, help_text='Whether upload option is available.'),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='has_view_details',
            field=models.BooleanField(default=True, help_text='Whether view details option is available.'),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags associated with the review.'),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='title',
            field=models.CharField(default='Review', help_text='Title of the review', max_length=255),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auditorreview',
            name='warning',
            field=models.TextField(blank=True, help_text='Warning message if additional information is required.'),
        ),
    ]
