# Generated by Django 5.2.5 on 2025-09-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0011_comment_parent'),
    ]

    operations = [
    ]
