# Generated by Django 5.2.5 on 2025-09-25 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0012_auto_20250924_2044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
