# Generated by Django 5.2.5 on 2025-09-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0013_evidence_created_by_evidence_updated_at'),
        ('compliance_monitoring', '0007_alter_project_owner_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorreview',
            name='sub_clause',
            field=models.ForeignKey(blank=True, help_text='The sub-clause this review is associated with. If null, review is for the main control.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='compliance_monitoring.subclause'),
        ),
    ]
