# Generated by Django 5.2.5 on 2025-09-27 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0014_auditorreview_sub_clause'),
        ('compliance_monitoring', '0007_alter_project_owner_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the todo task', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the todo task')),
                ('type', models.CharField(help_text="Type of task, e.g., 'User Management', 'Risk Management', etc.", max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', help_text='Priority level of the todo', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Required', 'Action Required'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of the todo', max_length=10)),
                ('category', models.CharField(choices=[('user_approval', 'User Approval'), ('risk_approval', 'Risk Approval'), ('auditor_assignment', 'Auditor Assignment'), ('evidence_approval', 'Evidence Approval'), ('policy_approval', 'Policy Approval'), ('Other', 'Other')], help_text='Category of the todo task', max_length=50)),
                ('due_date', models.DateField(blank=True, help_text='Due date for completing the todo', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details in JSON format (e.g., user info, risk details, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='The admin who created this todo. Only admins can access todos.', on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, help_text='The user assigned to complete this todo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project this todo is associated with (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='compliance_monitoring.project')),
                ('requester', models.ForeignKey(blank=True, help_text='The user who requested this todo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
