# Generated by Django 5.2.5 on 2025-09-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0015_todo'),
        ('compliance_monitoring', '0007_alter_project_owner_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance_monitoring.project'),
            preserve_default=False,
        ),
    ]
