# Generated by Django 5.1.3 on 2025-10-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0016_add_project_to_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver about the approval decision.'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The approval status of this evidence.', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this evidence was approved.', null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The user who approved this evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evidences', to=settings.AUTH_USER_MODEL),
        ),
    ]
