# Generated by Django 5.1.3 on 2025-10-09 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0017_evidence_approval_notes_evidence_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='actionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
