// Action types for ComplianceContext
export const ActionTypes = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_PROJECTS: "SET_PROJECTS",
  SET_RISKS: "SET_RISKS",
  SET_CONTROLS: "SET_CONTROLS",
  SET_EVIDENCE: "SET_EVIDENCE",
  SET_USERS: "SET_USERS",
  SET_AUDITORS: "SET_AUDITORS",
  SET_TODOS: "SET_TODOS",
  SET_FRAMEWORKS: "SET_FRAMEWORKS",
  UPDATE_ORGANIZATION_DATA: "UPDATE_ORGANIZATION_DATA",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  RESET_STATE: "RESET_STATE",
};
