export const questionnaireSections = [
  {
    heading: "1. Governance, Leadership & Policy",
    questions: [
      "Does your organization maintain formally documented policies for information security, privacy, AI governance, and regulatory compliance that have received senior management approval?",
      "Do executive leadership and board members take direct accountability for overseeing compliance and security risk management?",
      "Have you appointed specific compliance personnel (such as Data Protection Officers, Chief Information Security Officers, Privacy Officers) with clearly articulated roles and responsibilities?",
      "Has your organization completed a comprehensive mapping exercise to identify all applicable laws, regulations, and compliance frameworks relevant to your business operations?",
      "Have you established a formal governance committee or steering body with responsibility for security and privacy oversight activities?",
      "Do your information security policies demonstrate clear alignment with strategic business objectives and documented risk tolerance levels?",
      "Have you created a structured policy hierarchy that establishes clear relationships between enterprise, technology, and departmental policy documents?",
      "Do you maintain processes for tracking, investigating, and escalating policy violations to appropriate management levels?",
      "Have you implemented formal procedures for requesting policy exceptions that include risk evaluation, time-limited approvals, and alternative control measures?",
      "Are your organizational policies available in all languages used across your global operations?",
      "Have you established systematic processes for communicating policy updates to all relevant stakeholders throughout the organization?",
      "Do you track and enforce acknowledgment of policies by employees, contractors, and external parties?",
      "Have you integrated compliance policy requirements into operational procedures and detailed work instructions?",
      "Do you cascade regulatory compliance obligations into department-specific policies and operational procedures?",
      "Have you implemented benchmarking processes to compare your policies against industry standards and comparable organizations?",
      "Do you maintain policy performance indicators and key metrics to evaluate compliance program effectiveness?",
      "Do you subject policy exceptions to structured approval processes and conduct periodic reviews of their continued necessity?",
      "Do you review and update policies, procedures, and controls at minimum annually or following significant organizational changes?",
      "Have you established measurable security and compliance objectives with regular effectiveness reviews?",
      "Do you maintain systematic processes for monitoring and responding to evolving global regulatory landscapes?",
      "Have you implemented a centralized policy management repository with appropriate version control and access restrictions?",
      "Do you establish expiration dates for temporary policy exceptions and interim control measures?",
    ],
  },
  {
    heading: "2. Risk Management & Change Control",
    questions: [
      "Have you established comprehensive documented risk assessment methodologies that address regulatory, reputational, operational, and contractual risk categories?",
      "Do you conduct risk evaluations on regular schedules and in response to significant organizational, technological, or regulatory changes?",
      "Have you implemented risk treatment, monitoring, and acceptance procedures with designated ownership and accountability?",
      "Do you maintain a centralized risk register that includes assigned risk owners, mitigation strategies, implementation timelines, and review schedules?",
      "Have you implemented an enterprise risk management framework that incorporates cybersecurity and privacy risks into overall business risk management?",
      "Do you utilize standardized risk assessment methodologies such as ISO 31000, NIST frameworks, or Factor Analysis of Information Risk (FAIR)?",
      "Has your board approved formal risk appetite and tolerance statements that guide organizational decision-making?",
      "Do you calculate and monitor both inherent and residual risk levels for all identified threat scenarios?",
      "Have you established business impact analysis processes for critical organizational assets and business functions?",
      "Do you conduct threat modeling activities for new systems, applications, and business process implementations?",
      "Have you integrated operational risk management, compliance risk assessment, and cybersecurity risk evaluation processes?",
      "Do you formally assess and incorporate third-party and supply chain risks into your enterprise risk management program?",
      "Have you implemented processes for aggregating and reporting risk metrics to executive leadership and board members?",
      "Do you maintain current risk visualization tools such as heat maps and executive dashboards?",
      "Do you conduct stress testing and scenario analysis exercises for critical risk exposure areas?",
      "Have you established formal risk transfer strategies including appropriate insurance coverage evaluations?",
      "Do you subject significant organizational changes (such as major projects, technology implementations, or acquisitions) to comprehensive risk and compliance impact evaluations?",
      "Have you developed systematic approaches for managing risks associated with emerging threats including artificial intelligence, supply chain disruption, and geopolitical instability?",
      "Have you established a formal change advisory board that evaluates security and compliance implications of proposed changes?",
      "Do you maintain documented emergency change procedures that include appropriate risk controls and post-implementation review requirements?",
      "Have you integrated change management processes with vulnerability management and security assessment activities?",
      "Do you test and document rollback procedures for all critical system modifications?",
    ],
  },
  {
    heading: "3. Asset & Information Lifecycle Management",
    questions: [
      "Do you maintain current and regularly updated inventories of all information assets including data repositories, applications, devices, and both cloud-based and on-premises systems?",
      "Have you designated accountable asset owners and established clear acceptable use parameters for all information assets?",
      "Do you systematically identify and either approve or remediate unauthorized IT systems and bring-your-own-device arrangements?",
      "Have you deployed automated asset discovery and inventory management capabilities throughout your environment?",
      "Do you classify all organizational assets according to their business criticality, sensitivity levels, and operational value?",
      "Have you implemented structured asset lifecycle management covering the entire span from initial procurement through final disposal?",
      "Do you track and manage software licensing to ensure ongoing compliance with all vendor agreements and terms?",
      "Have you established a configuration management database that documents asset relationships and interdependencies?",
      "Do you maintain comprehensive inventories of cloud-based assets and services across all cloud service providers?",
      "Have you implemented processes for identifying and managing unowned or orphaned assets within your environment?",
      "Have you clearly defined asset ownership responsibilities including backup and deputy arrangements for continuity?",
      "Have you integrated asset management systems with vulnerability management and security assessment tools?",
      "Do you identify, classify, and appropriately protect intellectual property and proprietary assets?",
      "Have you established systematic processes for asset transfers during organizational restructuring or personnel departures?",
      "Do you track and report asset management performance indicators and key metrics to organizational leadership?",
      "Do you implement controls and monitoring for removable media, mobile devices, and cloud storage utilization?",
      "Have you established secure data destruction and erasure procedures for assets reaching end-of-life or upon contract termination?",
      "Do you regularly review and update data classification schemes to reflect evolving risks and asset portfolios?",
      "Have you implemented data retention and archival policies that align with legal obligations and business requirements?",
      "Do you maintain comprehensive documentation of data flows across all organizational systems and business processes?",
      "Have you established processes for identifying and managing personal data throughout its entire processing lifecycle?",
      "Do you apply data minimization principles to limit unnecessary data collection and long-term storage?",
      "Have you implemented data quality management processes including data integrity verification procedures?",
    ],
  },
  {
    heading: "4. Access Control & User Management",
    questions: [
      "Do you base all user access privileges, including administrative accounts, on least privilege principles with regular reviews and prompt revocation upon role changes or departures?",
      "Do you log, monitor, and independently review all privileged account activities and administrative actions?",
      "Have you enforced multi-factor authentication requirements for sensitive roles and critical system access?",
      "Do you prohibit or strictly control the use of shared or generic user accounts across your environment?",
      "Have you developed a comprehensive identity and access management strategy with centralized user account provisioning capabilities?",
      "Have you implemented role-based access control systems with regular role analysis and optimization activities?",
      "Do you enforce segregation of duties controls for critical business processes and sensitive operations?",
      "Have you deployed privileged access management solutions for all administrative and high-privilege accounts?",
      "Do you provide just-in-time access provisioning capabilities for temporary or emergency access requirements?",
      "Do you manage service accounts and non-human identities with appropriate security controls and oversight?",
      "Have you integrated human resources systems with access management for automated account provisioning and deprovisioning?",
      "Do you conduct regular access certification and attestation reviews by designated data and system owners?",
      "Have you implemented behavioral analytics and user activity monitoring for anomalous behavior detection?",
      "Do you manage contractor and third-party access rights separately with appropriate usage restrictions and monitoring?",
      "Have you established documented emergency access procedures with comprehensive logging and review requirements?",
      "Do you enforce password policies including complexity requirements and regular rotation schedules?",
      "Do you require session timeout controls for all critical applications and sensitive systems?",
      "Do you systematically detect and promptly remove dormant or unused user accounts?",
      "Do you audit failed login attempts and account lockout events for potential attack pattern identification?",
      "Have you implemented single sign-on capabilities where appropriate using secure federation protocols?",
      "Do you evaluate and implement biometric authentication methods where suitable for enhanced security?",
      "Have you deployed adaptive authentication systems that adjust requirements based on risk factors and user behavior patterns?",
    ],
  },
  {
    heading: "5. Data Protection, Privacy & Retention",
    questions: [
      "Do you identify, classify, and protect personal and sensitive data throughout all stages of its processing lifecycle?",
      "Do you conduct privacy and data protection impact assessments for all projects involving personal data or high-risk processing activities?",
      "Have you implemented data encryption for both stored and transmitted data, along with anonymization and pseudonymization techniques where appropriate?",
      "Do you provide operational support for all data subject rights including access, correction, erasure, and data portability requests?",
      "Have you completed comprehensive data mapping exercises that document all personal data processing activities across your organization?",
      "Do you clearly identify and document lawful bases for processing personal data for each specific processing purpose?",
      "Have you implemented privacy by design and privacy by default principles in all new system development and implementation processes?",
      "Do you conduct data protection impact assessments for high-risk processing activities with documented outcomes and mitigation measures?",
      "Have you established data breach response procedures with notification timelines that comply with all applicable regulatory requirements?",
      "Do you implement additional protection measures for special categories of personal data (sensitive personal information)?",
      "Have you established systematic processes for managing consent including mechanisms for consent withdrawal?",
      "Do you maintain data processing agreements with all third parties that process personal data on your behalf?",
      "Do you conduct regular monitoring and auditing of data processing activities to ensure ongoing compliance?",
      "Do you maintain clear and transparent privacy notices that are regularly updated to reflect changes in processing activities?",
      "Have you established procedures for responding to regulatory inquiries and conducting investigations?",
      "Do you specifically address children's data protection requirements where your processing activities may affect minors?",
      "Do you regularly review data collection forms and processes to ensure you avoid collecting unnecessary personal information?",
      "Have you defined, documented, and enforced data retention and deletion schedules across all organizational systems?",
      "Do you regularly audit third-party data processing activities for compliance with contractual obligations and legal requirements?",
      "Do you support cross-border data transfers with appropriate legal mechanisms such as Standard Contractual Clauses or Binding Corporate Rules?",
      "Have you implemented automated data retention and deletion capabilities across all systems and platforms?",
      "Do you include backup and archive systems in your data retention and deletion processes?",
      "Have you established data quality management programs to ensure ongoing accuracy and completeness of personal data?",
    ],
  },
  {
    heading: "6. Security Controls & Technology Measures",
    questions: [
      "Have you implemented, maintained, and monitored technical security controls including firewalls, encryption systems, anti-malware solutions, and patch management for ongoing effectiveness?",
      "Do you disable unnecessary services, protocols, and network ports across all organizational systems?",
      "Do you conduct and document network segmentation, segregation, and regular vulnerability and penetration testing activities?",
      "Do you require security reviews for all source code modifications and software changes before production deployment?",
      "Have you developed a comprehensive security architecture framework that aligns with your business requirements and risk profile?",
      "Have you implemented zero-trust network architecture principles throughout your technology environment?",
      "Do you deploy endpoint detection and response capabilities across all organizational endpoints and devices?",
      "Have you implemented security information and event management systems with correlation rules and automated alerting capabilities?",
      "Do you conduct network traffic analysis and monitoring for detecting anomalous behavior and potential threats?",
      "Have you deployed web application firewalls and database activity monitoring for all critical applications and data repositories?",
      "Do you maintain a systematic vulnerability management program with automated scanning and remediation tracking capabilities?",
      "Have you implemented security orchestration, automation, and response capabilities to improve incident response efficiency?",
      "Do you deploy data loss prevention technology to prevent unauthorized data exfiltration and information disclosure?",
      "Have you implemented cloud security posture management tools to continuously monitor cloud configuration compliance?",
      "Do you maintain container and Kubernetes security monitoring for all containerized application environments?",
      "Have you integrated threat intelligence feeds into your security monitoring and threat detection systems?",
      "Do you coordinate, test, and document all system and application updates before production deployment?",
      "Do you change all default system settings and credentials before placing systems into operational use?",
      "Have you established system hardening standards based on recognized industry benchmarks such as CIS Controls?",
      "Do you maintain security configuration baselines and monitor systems for configuration drift?",
      "Have you implemented automated patch management processes with appropriate testing and rollback procedures?",
      "Do you regularly scan systems for compliance with established security configuration standards?",
      "Have you implemented automated backup processes that include offsite or immutable copies for all critical systems?",
      "Do you collect, protect against tampering, and analyze log data for anomalous activity detection?",
      "Do you regularly test backup and recovery processes with documented results and performance metrics?",
      "Have you implemented air-gapped backup storage capabilities to protect against ransomware and destructive attacks?",
    ],
  },
  {
    heading: "7. Third-Party & Supplier Management",
    questions: [
      "Do you assess third-party vendors and processors for security and compliance capabilities before onboarding and on regular ongoing schedules?",
      "Do you require third-party adherence to your organizational code of conduct or equivalent ethical and security standards?",
      "Have you established contracts with all suppliers and sub-processors that specify detailed security, privacy, and compliance requirements?",
      "Do you collect and review suppliers' security certifications and independent audit reports on a regular basis?",
      "Have you established a systematic vendor risk management program with standardized assessment criteria and evaluation processes?",
      "Do you conduct appropriate due diligence procedures that vary based on supplier risk categories and criticality levels?",
      "Do you maintain ongoing monitoring of supplier security posture and compliance status throughout the relationship?",
      "Do you track supplier performance metrics and service level agreements including security and privacy key performance indicators?",
      "Have you established supplier incident response and communication protocols for security and privacy events?",
      "Do you assess and manage fourth-party risks (sub-processor relationships) with appropriate oversight and controls?",
      "Have you implemented systematic supplier onboarding and offboarding processes that include security requirement verification?",
      "Do you conduct regular benchmarking of supplier security practices against industry standards and best practices?",
      "Have you conducted supplier concentration risk assessments to avoid excessive dependence on single vendors?",
      "Do you consider geopolitical risks and supply chain security factors in your supplier selection and management processes?",
      "Have you established systematic processes for supplier security incident notification and coordinated response activities?",
      "Do you maintain current and comprehensive lists of all third-party processors and service providers?",
      "Do you regularly review suppliers' business continuity and disaster recovery capabilities and planning?",
      "Have you implemented software supply chain security management including tracking of open source components and dependencies?",
      "Do you assess supplier facilities and physical security controls where appropriate to your risk profile?",
      "Have you integrated supplier risk management activities with your enterprise risk management program?",
    ],
  },
  {
    heading: "8. Incident, Breach Response & Preparedness",
    questions: [
      "Have you developed, documented, and regularly tested incident response and breach notification procedures?",
      "Do you report, investigate, and remediate security incidents promptly with appropriate evidence handling and forensic readiness capabilities?",
      "Do you conduct incident response drills, tabletop exercises, and scenario-based simulations with lessons learned integration into response procedures?",
      "Have you established clear communication protocols for incident escalation and notification to internal and external stakeholders?",
      "Do you maintain 24/7 security operations center capabilities or equivalent incident response readiness?",
      "Have you clearly defined incident response team roles and responsibilities with designated backup personnel?",
      "Have you integrated incident response procedures with broader crisis management and business continuity processes?",
      "Do you maintain clear documentation of legal and regulatory notification requirements with specific timelines?",
      "Have you implemented systematic incident classification and prioritization frameworks?",
      "Do you maintain forensic investigation capabilities either internally or through established third-party arrangements?",
      "Have you integrated media relations and public communications coordination into incident response procedures?",
      "Do you maintain pre-prepared customer and stakeholder communication templates for different types of security incidents?",
      "Do you conduct systematic post-incident reviews and lessons learned documentation with specific improvement actions?",
      "Do you test incident response procedures against various attack scenarios and emerging threat vectors?",
      "Have you established coordination procedures with law enforcement and regulatory authorities as required?",
      "Do you track and report incident response metrics and performance indicators to senior management?",
      "Do you conduct root cause analysis for all incidents, near-misses, and breaches with systematic tracking of corrective actions?",
      "Have you integrated incident response procedures with business continuity activation and crisis management processes?",
      "Do you coordinate incident response procedures with disaster recovery and business continuity planning activities?",
      "Have you identified alternative communication methods for use during major incidents affecting primary communication systems?",
    ],
  },
  {
    heading: "9. Training, Culture & Awareness",
    questions: [
      "Do you provide mandatory, documented security and privacy training for all personnel at hire and on regular recurring schedules?",
      "Do you track training completion, enforce compliance requirements, and customize training content for specific roles and responsibilities?",
      "Do you conduct regular awareness campaigns and simulated threat exercises such as phishing simulations for all staff members?",
      "Do you promptly update staff on changes in applicable laws, organizational policies, and industry best practices?",
      "Have you developed a systematic security awareness program strategy that aligns with your organizational risk profile and threat landscape?",
      "Do you customize training materials for different organizational roles, departments, and individual risk exposure levels?",
      "Do you measure training program effectiveness through testing, simulation exercises, and behavioral change metrics?",
      "Do you include third-party contractors and temporary staff in your security awareness and training programs?",
      "Do you provide specialized training for high-risk roles including developers, system administrators, and executive leadership?",
      "Do you incorporate emerging threats and evolving attack techniques into your awareness training content and materials?",
      "Have you implemented gamification techniques or incentive programs to encourage security-conscious behavior throughout the organization?",
      "Do you track and report security awareness metrics and program effectiveness to management on regular schedules?",
      "Have you integrated security awareness initiatives with broader corporate culture and values programs?",
      "Do you maintain security champion or ambassador programs within different departments and business units?",
      "Do you regularly communicate appropriately sanitized security incidents and lessons learned to reinforce awareness objectives?",
      "Do you provide security awareness materials in multiple languages to accommodate your diverse workforce needs?",
      "Do you provide confidential channels for employees to report compliance concerns and ethical issues without fear of retaliation?",
      "Have you established protection mechanisms against retaliation for good faith security and compliance reporting?",
      "Do you regularly communicate the business importance and value of security and privacy to organizational success?",
      "Have you integrated security and privacy considerations into employee performance management and evaluation processes?",
    ],
  },
  {
    heading: "10. Business Continuity, Resilience & Physical Security",
    questions: [
      "Have you documented business continuity and disaster recovery plans for all critical operations with regular testing and validation?",
      "Do you test and document backup, restoration, and recovery processes for effectiveness and reliability?",
      "Have you incorporated remote and hybrid work arrangements into your continuity planning and policy framework?",
      "Do you test critical business processes for resilience under various threat scenarios and disruption events?",
      "Have you conducted comprehensive business impact analysis with defined recovery time objectives and recovery point objectives?",
      "Do you maintain mapping of dependencies and interdependencies for all critical business processes and systems?",
      "Have you established geographic dispersion of critical operations and backup facilities to ensure continuity?",
      "Do you maintain alternative supplier arrangements for critical services and materials to mitigate supply chain disruption?",
      "Have you developed crisis communication planning that addresses both internal and external stakeholder needs?",
      "Have you integrated business continuity plans with cybersecurity incident response and crisis management procedures?",
      "Do you conduct regular testing of business continuity plans using different scenarios and threat vectors?",
      "Have you assessed business continuity capabilities for distributed operations and remote work environments?",
      "Do you maintain coordination procedures with public authorities and emergency services where appropriate?",
      "Do you measure and report business continuity metrics and recovery capabilities on regular schedules?",
      "Have you incorporated employee welfare and safety planning into your continuity procedures and crisis response?",
      "Do you systematically incorporate lessons learned from business continuity events into plan improvements and updates?",
      "Have you implemented appropriate physical and environmental controls for all organizational facilities including visitor management, access logging, surveillance systems, and environmental monitoring?",
      "Do you regularly assess the resilience of key suppliers and broader supply chain relationships?",
      "Do you protect data centers and critical facilities with comprehensive physical security measures and access controls?",
      "Have you implemented environmental monitoring and alerting systems for temperature, humidity, and power conditions?",
      "Do you enforce clean desk and clear screen policies throughout all work areas and facilities?",
      "Have you established secure destruction procedures for physical documents and storage media?",
      "Do you assess alternative work locations for appropriate security controls and compliance with organizational standards?",
    ],
  },
  {
    heading: "11. Monitoring, Auditing & Continuous Improvement",
    questions: [
      "Do you subject controls, systems, and processes to regular internal audits, external assessments, and independent reviews?",
      "Have you established ongoing log monitoring and automated alerting capabilities for anomalous activity detection with continuous tuning and optimization?",
      "Do you maintain systematic continuous improvement processes that incorporate lessons learned from audits, incidents, and regulatory changes?",
      "Do you assign ownership to audit findings, track them through closure, and include results in senior management reporting?",
      "Have you established a systematic internal audit program with qualified personnel and appropriate organizational independence?",
      "Do you engage qualified third-party assessors to conduct external audits and assessments on regular schedules?",
      "Have you integrated various audit and assessment activities to minimize duplication and maximize efficiency?",
      "Do you align audit methodologies with relevant standards and frameworks such as ISO 27001, SOC 2, and industry-specific requirements?",
      "Have you implemented systematic management response processes for audit findings with defined remediation timelines?",
      "Do you communicate audit results to appropriate stakeholders including board members and senior management?",
      "Do you conduct trending analysis of audit findings to identify systemic issues and improvement opportunities?",
      "Have you documented control testing procedures with consistent application across all assessment activities?",
      "Do you maintain control self-assessment programs to complement formal audit activities?",
      "Do you retain audit evidence and documentation according to regulatory and legal requirements?",
      "Have you established coordination between internal audit, external audit, and regulatory examination activities?",
      "Do you track audit findings in centralized systems with workflow management and reporting capabilities?",
      "Do you participate in sector-specific and government security intelligence sharing programs and initiatives?",
      "Have you implemented automated compliance monitoring with real-time dashboards and alerting capabilities?",
      "Do you maintain key risk indicators and key performance indicators with ongoing monitoring and reporting?",
      "Do you conduct regular benchmarking activities against industry peers and recognized best practices?",
      "Have you established systematic lessons learned processes for incorporating insights from incidents and audit activities?",
    ],
  },
  {
    heading: "12. Advanced/Industry- or Tech-Specific Controls",
    questions: [
      "For organizations processing payment data: Do you meet PCI DSS requirements for cardholder data flow mapping, secure storage, access controls, encryption implementation, and comprehensive logging with regular testing?",
      "Have you implemented network segmentation to isolate cardholder data environments from other network segments?",
      "Do you conduct vulnerability management and penetration testing activities regularly for all systems within PCI scope?",
      "Have you implemented file integrity monitoring for critical system files and configuration settings?",
      "For healthcare organizations: Do you maintain HIPAA compliance, HITRUST framework alignment, or ISO 27799 control mappings with appropriate evidence documentation?",
      "Have you implemented risk assessment processes specifically designed for protected health information handling and processing?",
      "Do you maintain business associate agreements with all third parties who handle protected health information on your behalf?",
      "Have you implemented audit logging and monitoring specifically for protected health information access and disclosure activities?",
      "Do you maintain security controls for medical devices and healthcare technology systems?",
      "For cloud and SaaS environments: Do you maintain CSA STAR certification or SOC 2 control attestation with ongoing monitoring and compliance validation?",
      "Have you established cloud security architecture review and approval processes for all cloud implementations?",
      "Do you conduct regular security assessments of cloud service providers and their security capabilities?",
      "Do you maintain compliance with data residency and sovereignty requirements for all cloud-stored information?",
      "Have you implemented cloud access security broker controls where appropriate for your cloud usage patterns?",
      "Do you maintain security monitoring and controls for container and serverless computing environments?",
      "Have you integrated threat intelligence feeds into your security monitoring and threat detection systems?",
      "For financial sector organizations: Do you address sector-specific business continuity, Digital Operational Resilience Act (DORA), Reserve Bank guidelines, or other financial regulatory obligations with appropriate regulatory reporting?",
      "Have you implemented operational resilience testing and reporting as required by financial services regulators?",
      "Do you integrate market conduct and consumer protection requirements into your security and privacy control framework?",
      "Have you implemented data protection controls for anti-money laundering and know-your-customer information?",
      "Do you maintain security controls and market abuse detection capabilities for trading systems and financial transactions?",
      "For AI system implementations: Do you systematically assess risks, monitor for bias and fairness, ensure explainability and transparency, and embed human oversight with comprehensive auditability?",
      "Have you established AI model governance including version control, testing procedures, and approval processes?",
      "Do you document and validate AI training data sources for quality assurance and appropriateness?",
      "Have you implemented ongoing monitoring of AI system performance with drift detection and alerting capabilities?",
      "Do you maintain human review and override capabilities for AI decision-making processes affecting individuals?",
      "Do you conduct algorithmic impact assessments for AI systems that affect individual rights or opportunities?",
      "Have you defined and implemented AI ethics principles throughout the complete AI system lifecycle?",
      "For critical infrastructure organizations: Do you address NIS2 Directive requirements, essential service provider obligations, supply chain security, and operational resilience requirements in compliance reviews?",
      "Do you maintain compliance with sector-specific cybersecurity frameworks such as NERC CIP for energy sector organizations?",
      "Have you implemented critical infrastructure protection measures for operational technology systems and industrial control systems?",
      "Do you maintain coordination with national cybersecurity authorities and participate in relevant information sharing organizations?",
      "Have you implemented supply chain security requirements specific to critical infrastructure protection and resilience?",
    ],
  },
  {
    heading: "13. Ethics, Transparency & Societal Impact",
    questions: [
      "Have you implemented fair, explainable, and bias-minimized decision-making practices in artificial intelligence and automated decision systems?",
      "Do you publish transparency reports for regulators and customers regarding data processing activities, complaint handling, and third-party information requests?",
      "Do you explicitly assess the impact of your operations and technology systems on vulnerable populations including children, elderly individuals, and marginalized communities?",
      "Have you established systematic processes for identifying, handling, and remediating ethical risks inherent in your technology implementations and business models?",
      "Have you established formal ethics committees or review boards for technology implementation and data utilization decisions?",
      "Do you conduct human rights impact assessments for data processing activities and AI system implementations?",
      "Do you engage stakeholders and conduct consultation processes on ethical technology use and data practices?",
      "Have you implemented algorithmic accountability measures including comprehensive audit trails and decision documentation?",
      "Do you regularly assess the societal impact of your business operations and technology implementations?",
      "Have you integrated ethical considerations into product and service design processes from initial conception?",
      "Do you maintain systematic processes for ethical dilemma resolution and appropriate escalation procedures?",
      "Do you provide ethics training and awareness programs for all employees and relevant stakeholders?",
      "Do you measure and report ethical performance metrics and accountability indicators?",
      "Do you conduct community impact assessments for major technology deployments and business changes?",
      "Have you integrated ethics functions with legal and compliance departments for coordinated oversight?",
      "Do you regularly publish transparency reports on government information requests and law enforcement cooperation activities?",
      "Do you provide data processing transparency measures to individuals and regulatory authorities?",
      "Do you publicly report on AI system performance metrics, bias testing results, and fairness evaluation outcomes?",
      "Have you implemented transparent and accessible complaint handling and resolution processes?",
      "Do you conduct regular stakeholder consultation on privacy practices and ethical technology implementations?",
    ],
  },
  {
    heading: "14. Emerging Technologies and Future Readiness",
    questions: [
      "Have you established systematic processes for assessing security and privacy risks associated with emerging technologies and innovations?",
      "Do you consider quantum computing implications for encryption technologies and security architecture in long-term strategic planning?",
      "Do you evaluate blockchain and distributed ledger technology implementations for security and privacy implications?",
      "Have you implemented security and privacy controls for Internet of Things devices and connected systems?",
      "Do you assess metaverse and virtual reality implementations for privacy and security risk implications?",
      "Have you formally assessed biometric technology implementations for associated risks and privacy implications?",
      "Do you monitor and prepare for upcoming regulatory changes including AI governance legislation and evolving privacy requirements?",
      "Have you established regulatory horizon scanning and impact assessment processes for emerging compliance obligations?",
      "Do you engage with regulatory bodies and industry associations regarding emerging requirements and best practices?",
      "Have you designed compliance programs to be adaptable and responsive to new regulatory requirements?",
      "Do you regularly review global regulatory trends that may affect your organization's operations and compliance obligations?",
    ],
  },
];
